version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - ${BACKEND_EXPOSED_PORT}:${BACKEND_INTERNAL_PORT}
    volumes:
      - "../backend:/backend"
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    build: ../frontend
    ports:
      - ${FRONTEND_EXPOSED_PORT}:${FRONTEND_INTERNAL_PORT}
    volumes:
      - ../frontend:/app
    env_file:
      - .env
  db:
    image: postgres
    volumes:
      - '../db/data:/var/lib/postgresql/data'
    ports:
      - ${DB_EXPOSED_PORT}:${DB_INTERNAL_PORT}
    environment:
      - POSTGRES_PASSWORD=Reflectometer
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "postgres",
          "-h",
          "localhost",
          "-p ${DB_INTERNAL_PORT}",
          "-U postgres"
        ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
